### ISSUE TITLE
Leftovers

### ISSUE THREAD

**Issue by BorealisPhoenix** [simon-82/ModVarietyPack#36]
I have from time to time an issue where the previous world will carry over into a new game and the people from the previous world will be in rosters or outfits and my new people are not there. It also glitches out stockpiles and other things.

Also, I am sure you are crazy busy between real life and smashing bugs but have you given any thought to multi resourced prison bars? :D

Don't know if this would ruin the balance of the game. but is their a way to make it so that human meat put in the food synthesizer does not get seen as human. For realism  something synthesized into a protean paste is no longer human. 

Edit: The problem is always fixed after making a save then restarting the game. 
More Edit: Also having trouble with the Mai mod auto crafting Mai

**Comment by simon-82** [comment]
1. I don't quite understand your first issue. Can you elaborate on that?
2. What are "multi resourced prison bars" ? 
3. Hm, not sure aout that. I mean they don't like the nutrient paste anyways. But they put the human meat into the machine. So they know it was a human they are eating. I think changing that would be not balanced tbh.
4. Your first issue is fixed then? Lol I didn't even understand that issue, sorry. But glad it gets fixed. If you could explain a bit more?
5. What is that trouble?

**Comment by BorealisPhoenix** [comment]
1. Make a colony then play colonyWe'll say their names are A, B, and C. Colony either dies or get s bad enough that I say hell with it. Make a new colony with 3 new people D, E, and F. I go to the outfits menu or some other menu where I can see my colonist list and instead of seeing D E F I see A B and C in the menu.
2. Jail bars similar to the the fences but made of steal, plasteel, aluminum, wood, etc... This way instead of having a bedroom you keep them in it's a jail. plus you have the added ability to take them out if they berserk from on the other side of the bars. like you can with a fence. Up to now I have been using wooden fences.
3. I know I agree. My friend who plays it wanted me to add that.
4. Not fixed unless you close the game to desktop then restart. This could be a vanilla issue; I am not sure.
5. With a little messing around I figured out that the Mai auto builder will not build if you don't have a person with a craft skill high enough while at the same time that person can not have ANYTHING else to do other than go to that station. Otherwise the machine won't start. I had to suspend ever other crafting station and anything else that used crafting skill then the person with the high enough skill then the station would start up. Until I figured this out the station sat their for little over a year with all the silver and steel in it and the green button turned on. Their is not right click support to just send someone over to it.

Love the new update.

**Comment by BangUDie** [comment]
HI,
I think 1 and 4 are something to do with EDB User-interface storing colonists until game reload somewhere... have not had it happen often enough to track it down as reloading fixes it.
For 3 you could add the Soylent green mod https://ludeon.com/forums/index.php?topic=5450.0 (Updated link I tested to work on page 24) Adding that in this way would be balanced in that tossing bodies in the soylent machine prevents leather and it sells for next to nothing.

For 2 it sounds like a copy of the Fence Def files with a change to be made of stuff and renamed could work, though the texture would probably need modification and not sure if the pawns would use it as a 'jail bar'. Though if that works for your usage im sure thats fine

As for 5. I know stockpile priority being critical can cause a problem, or when bought the MAI builder can sometimes not initialize properly (thought that bug was fixed - had this issue myself) as the thing that builds the MAI should be automatic once filled.

**Comment by BorealisPhoenix** [comment]
1.I'll look into the mod 
2. From what I can tell the fence works like a wall for the purpose of having a prison room. So having a re texture and have different materials to make it out of would be all you'd need. Temped to learn some programming to make this mod. I have only ever modded on Project Zomboid.

**Comment by BangUDie** [comment]
Should be all XML based for what you would be looking to do so....
==== Rough rundown ====

Take the files you want to change and put them in a folder (/yourmod or something) and keep the directory structure intact (for example take the relevant bits from the the fences and put them like this Mods\YourNameMod\Defs\ThingDefs\xml_file_they_live_in) 
The texture should still exist if you load your mod after the original mod it came from without making your own copy.
Cant walk you through it much here but if you wanted you could pop in the modder slack, there is usually someone around to help out. ( reference this post if your interested https://ludeon.com/forums/index.php?topic=14501.0  )

**Comment by BorealisPhoenix** [comment]
Tank you man.

**Comment by Karel-Kroeze** [comment]
The first issue with 'ghost' pawns is probably the same problem as the generally known 'reload the game after changing mods' - modded assemblies are not getting properly destructed/re-instantiated, so any static variables linger around. I think.
